### ISSUE TITLE
Accessing services using IP and port

### ISSUE THREAD

**Issue by sourav82** [mesosphere/kubernetes-mesos#115]
I had 2 minions - 10.227.125.10 & 10.227.125.3 and scheduled pods containing one docker container of a web app on these 2 minions. I kept 3 replicas of the pod. The container exposes port 80 and I mapped container port 80 to port 31020 on host. I created one service for these pods which binds to port 8000. I'm trying to access 10.227.125.10:8000 from IE.

Problem is, as the container port 80 mapped to host port 31020, there will be port conflict while trying to schedule 3rd replica of the pod in any one of those 2 minions. Could you please let me know any workaround here? 

If I do not specify any host port in the pod template, then I'm not able to access the container application from IE. Do I always need to map container port to host port in podTemplate?

I read in the document, there is something called service IP. How can I set up the service IP and make it accessible from outside (on intranet)?

**Comment by jdef** [comment]
Regarding replication control:

Currently, given default (host-private) Docker networking model, it's a
requirement that pods must expose host ports if they want to back a
service. Host ports for pods are allocated from the "ports" resource on
each slave, which is why you cannot run more than 2 replicas of your pod
across only 2 slaves. There's some ongoing development work that explores
options for dynamically allocating host ports but it's not usable yet.

That said, if you are managing the IP address of your Docker bridges
independently of the defaults, **and** those IPs are resolvable across your
network, then you can bypass the "exposed host port" requirement by
reverting to stock kubernetes behavior in the controller-manager using
the -host_port_endpoints=false flag. Do not do this if you are using
default Docker networking or else your services will be broken.

Regarding service IPs:

Kubernetes introduced service portals, which follows an IP-per-service
model: each service is assigned an IP address from the "portal network",
which is defined when the kubernetes master is started up (portal_net
parameter). Each node that runs kube-proxy will set up iptables rules that
listen for connection attempts to these service IP addresses. Upon
connecting to a service IP from a host running kube-proxy, packets are
forwarded to a listener socket of the kube-proxy process, which then
establishes a connection with the listening socket on the pod, and proceeds
to proxy the connection. So basically: client --> service-IP/iptables -->
kube-proxy --> pod.

Service-IP's are, generally, not intended to be exposed to the internet.
You **can** specify a `PublicIPs` field in your service specification,
which can contain any IP addresses that you like. For example, the public
IPs could be the addresses of some frontend load balancer services that
will forward traffic to your slaves.


On Tue, Jan 6, 2015 at 11:51 PM, sourav82 <notifications@github.com> wrote:

> I had 2 minions - 10.227.125.10 & 10.227.125.3 and scheduled pods
> containing one docker container of a web app on these 2 minions. I kept 3
> replicas of the pod. The container exposes port 80 and I mapped container
> port 80 to port 31020 on host. I created one service for these pods which
> binds to port 8000. I'm trying to access 10.227.125.10:8000 from IE.
>
> Problem is, as the container port 80 mapped to host port 31020, there will
> be port conflict while trying to schedule 3rd replica of the pod in any one
> of those 2 minions. Could you please let me know any workaround here?
>
> If I do not specify any host port in the pod template, then I'm not able
> to access the container application from IE. Do I always need to map
> container port to host port in podTemplate?
>
> I read in the document, there is something called service IP. How can I
> set up the service IP and make it accessible from outside (on intranet)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mesosphere/kubernetes-mesos/issues/115>.
>



-- 
James DeFelice
585.241.9488 (voice)
650.649.6071 (fax)

**Comment by sourav82** [comment]
@jdef Thanks a lot for explaining in detail. Really helped in understanding the behavior.
