### ISSUE TITLE
scheduler and controller-manager /healthz endpoints missing

### ISSUE THREAD

**Issue by jdef** [mesosphere/kubernetes-mesos#229]
scheduler and controller-manager should provide HTTP /healthz endpoints, just like the apiserver. they don't appear to be doing that.

**Comment by sttts** [comment]
The PR by joerg should be ported to the upstream repo

**Comment by sttts** [comment]
For the moment in the v1 dcos packages we use the apiserver healthz endpoint for the moment.

**Comment by s-urbaniak** [comment]
TODOs:

controllermanager:
- [x] implement general healthz registration by registering controllermanager controllers
- [ ] implement ​`healthz.HealthzChecker`​ for controllerManager
- [ ] implement ​`healthz.HealthzChecker`​ for nodeController
- [ ] implement ​`healthz.HealthzChecker`​ for resourceQuotaController
- [ ] implement ​`healthz.HealthzChecker`​ for namespaceController
- [ ] implement ​healthz check for apiserver readiness (invoking simple get request)

for scheduler:
- [ ] healthz check for master offers

**Comment by karlkfi** [comment]
I already have code that adds healthchecks on the component-registration branch. I didn't realize there was a ticket for it. You could just go grab some of that code. 

That said, there's init() functions in most of the main functions that are effectively useless, because unlike the vanilla components, the k8sm components don't use the default mux.

**Comment by s-urbaniak** [comment]
Thanks @karlkfi, I'll have a look at that code!

**Comment by s-urbaniak** [comment]
@karlkfi Thanks for the pointer, I went through the code (https://github.com/kubernetes/kubernetes/compare/master...mesosphere:component-registration#diff-63ef6c53d60fa322e771d1cfc096ec8bR33). It seems you only registered the standard healthz endpoint aka `healthz.DefaultHealthz()` in the scheduler. If that makes sense (no transient service checks) I can simply do the same in my branch.

In the controller manager I'm doing the following:
- health checks for controllerManager, nodeController, resourceQuotaController, namespaceController (iff they implement HealthzChecker interface)
- api server healthz check by invoking a GET towards `/api` (according to @sttts's suggestion)
- The default `healthz.PingHealthz`

So far I have it working locally for the controllermanager.

Question: Does it make sense when fixing this issue to also implement the HealthzChecker interface the above mentioned controllers? Currently none of them implements it.

**Comment by karlkfi** [comment]
Last I checked the controller-manager and apiserver already had /healthz endpoints. So I only added one to the scheduler. 

You're right that the default /healthz does no transitive dependency checks. I would like them to, but it wasn't high priority at the time, and vanilla k8s doesn't either. 

I'm not sure it makes sense to add /healthz endpoints to individual controllers until they're broken out to separate processes. Until then it would be better for a controller failure to crash the whole controller-manager, but I'm not sure that's implemented either (except on panic).

I don't know what the HealthzChecker interface is. So I can't answer those questions without doing some more research.

**Comment by s-urbaniak** [comment]
@karlkfi Thanks a lot for your comments, I'll throw out the controller checks for now, only leaving the api-server and ping check.

In the api-server besides the ping health check I am adding a watchdog health check for offered resources.

**Comment by karlkfi** [comment]
> besides the ping health check I am adding a watchdog health check for offered resources.

Can you expand on the difference and specific endpoints?

**Comment by s-urbaniak** [comment]
@karlkfi as discussed yesterday: the `healthz.InstallHandler(mux, ...HealthzChecker)` function installs by default a `/healthz` and `/healthz/ping` endpoint if no `HealthzChecker`s are provided.

The above mentioned endpoints satisfy the requirement for a liveness check and are already implemented in the controllermanager. I'll open a PR implementing the same for the scheduler.

To implement readiness checks we could piggy-pack on the existing `healthz` semantics, which will fail with a HTTP code `500` at the root `/healthz` endpoint if at least one of the checkers fails. (see https://github.com/kubernetes/kubernetes/blob/master/pkg/healthz/healthz.go#L109)

The dedicated `/healthz/ping` will never fail preserving the requirement for a liveness check.

To satisfy the readiness requirement I'll keep on working on a separate branch and suggest the following proposal:
- *controllermanager*: GET request towards the api-server (@karlkfi's proposal is to use `/health` implying readiness of the api-server)
- *scheduler*: A watchdog for resource offers reachable under `/healthz/resources`. This healthz endpoint will fail if the scheduler does not get resources offered in time (i.e. `KubernetesScheduler. ResourceOffers ` was not being invoked in the last x seconds, see https://github.com/kubernetes/kubernetes/blob/master/contrib/mesos/pkg/scheduler/scheduler.go#L364)

**Comment by jdef** [comment]
I really like the idea of a scheduler readiness check. I'm a bit conflicted
about the use of a time window re: timeliness of resource offers: obviously
if we're not receiving offers then we can't schedule anything and our
scheduler is not very useful - but the scheduler could be totally healthy
and something else could be misconfigured (resources roles; other, more
greedy schedulers in the cluster, etc).

In addition, I believe that users can configure the allocation interval on
the master (and I'm not sure how discoverable this is, externally) so if we
*did* want scheduler readiness based on resource offers, we'd want to
parameterize whatever time window we're using as a threshold so that user's
can tweak this if needed (for "evil tuning" tweaks like this there's an
optional scheduler configuration file that we support).

/healthz/ping makes perfect sense for liveness.

Is it worth considering health (readiness) states other than pass/fail? For
example, pass/warning/fail?


On Tue, Sep 15, 2015 at 7:10 AM, Sergiusz Urbaniak <notifications@github.com

**Comment by s-urbaniak** [comment]
@jdef thanks for your comments. When saying "x seconds" timeout I implicitly was assuming "configurable" in my head, I should have been more explicit about this.

We could consider other health states for readiness but then the current `healthz` package is not sufficient. Currently it makes binary decisions "healthy/not healthy" only so we either extend the current `healthz` package (is this feasible at the current state of k8s?) or do readiness checks outside of `healthz`.

Any ideas are welcome :-) I'm still in the "not yet having the global-picture mode" yet ;-)

**Comment by jdef** [comment]
@karlkfi thoughts re: health states other than pass/fail?

**Comment by sttts** [comment]
Some thought: we want to use the readiness in the dcos marathon task. A bad readiness will eventually trigger a restart through marathon. It would be nice to have a third state "not health, but restarting will not fix the problem". Marathon supports http 100, but this does not fit here.

**Comment by karlkfi** [comment]
I don't think the scheduler should depend on resource offers for readiness. That would be like HDFS reporting NotReady if its nodes were full or Spark reporting NotReady if it was too busy to schedule more jobs. These are all temporary states that are better exposed by a metrics endpoint so that the operator can set up custom alerts with external logic like "alert if the average time to schedule new tasks is > 5m".

As for health states, I want to be analogous with the k8s Pods and be able to check both liveness and readiness.

Liveness means that the server is up, running, (in the case of remote-only checking) accessible via the network, and (in the case of an http(s) get request) responding to requests. 

Readiness means that the server is alive, functioning as expected, and has confirmed that its immediate dependencies are also ready.

Having looked at the existing `/healthz` impl in k8s, I think it's reasonable to use the root `/healthz` to indicate service readiness, because it supports the composition and aggregation of a list of custom readiness checks (`HealthzChecker` impls).

Given that, there's two options for testing liveness: either just open and close a tcp connection to `/healthz` or perform an http(s) get to `/healthz/ping`, which immediately responds with a successful status code.

The action taken by the operator or automation in response to Liveness and Readiness failures is debatable, but in general:
- A service that is NotAlive needs to be immediately restarted (or re-scheduled, or re-deployed) provided an initial bootstrapping timeout has passed or the service was previously Alive.
- A service that is Alive but NotReady might recover on its own, but may also be restarted if a much longer timeout has been reached or if its dependencies are all known to be Ready.

**Comment by sttts** [comment]
The point is that I have seen cases with Kubernetes, but also with Marathon, that the scheduler got stuck somehow. Maybe it was not registered anymore in the eyes of the Mesos master. This kind of failure is fatal for the scheduler or must be detected by some watchdog mechanism, e.g. by counting the time since the last offer. This definitely belongs into a health check.

**Comment by karlkfi** [comment]
On caveat with Liveness is that there's a slight difference between local Liveness (process pid checking) and remote Liveness (tcp connection or http(s) get), because a process might be locally Alive, but remotely NotAlive in a few cases (e.g. network partition, configuration problem).

As for @sttts's point about getting stuck, I still think that should be in an external monitoring tool that is responding to changes over time from a `/metrics` endpoint and a custom operator specified policy.

However, the scheduler readiness should definitely depend on the readiness of Mesos, but how Mesos responds to a ready check is up to Mesos.

I'm ok with a request/response being performed, but I don't think it's reasonable to have a readiness endpoint take a long time to respond. Liveness and Readiness checks do not guarantee that the service is Alive or Ready, they are canaries in coal mines that only mean something when they are dead/failing.

**Comment by karlkfi** [comment]
Superseded by #499
