### ISSUE TITLE
Make scheduler behavior more configurable

### ISSUE THREAD

**Issue by ConnorDoyle** [mesosphere/kubernetes-mesos#237]
There are a number of constant "default" values that cannot currently be configured in the scheduler (see the values in [scheduler.go](https://github.com/mesosphere/kubernetes-mesos/blob/master/pkg/scheduler/scheduler.go#L36)).

We could add flags, read them from a config file (or both).  For reference, here's how the cloud provider will read config from a file with gcfg: https://github.com/mesosphere/kubernetes-mesos/blob/437d0bc4c8c48f3220d589e9ea82fde3edfa4485/pkg/cloud/mesos/config.go.

CC @sttts

**Comment by sttts** [comment]
Will take care of it. Please assign to me if possible.

**Comment by ConnorDoyle** [comment]
If we can also make the framework name configurable as part of the patch set that addresses this, let's get it in.  That should be considered fairly high priority.

@sttts I cannot assign the issue to you unfortunately... let me look into adding you as a collaborator on this project.

**Comment by jdef** [comment]
@ConnorDoyle FWIW when you and I had talked the other day about framework-name, I failed to properly articulate my concern at the time. The framework-id is stored in etcd at a fixed location, whereas other things are preserved in etcd (leader election) at a variable path determined by framework-name.

In the end this probably isn't a huge deal since running multiple instances of k8s on top of the same etcd cluster is a death-wish: the path at which the framework-id is stored would be the least of the problems.

**Comment by ConnorDoyle** [comment]
Hey James. Slightly related: I've been thinking about providing a DWS (distributed watchable storage) provisioner framework. You would ask this thing to launch an etcd/consul/zk quorum for you on the cluster.  Something could be prototyped relatively quickly but we'd need to resource this project properly to take it beyond the initial stages though.

**Comment by jdef** [comment]
Hi Connor,

Over the past several weeks I've considered something similar, specifically
with respect to etcd. It would certainly help k8s on dcos! If you're
looking for help, I'm in.

-James
