### ISSUE TITLE
Update the upstream_k8sm docs/getting-started-guides/mesos.md

### ISSUE THREAD

**Issue by sttts** [mesosphere/kubernetes-mesos#295]
E.g. the `km` binary does not exist. The described walk-through must be tested.

**Comment by jdef** [comment]
the km binary will exist if user's are still building the kubernetes-mesos
project.

I didn't port the 'km' binary upstream because of the dependency on
k8sm-controller-manager, which I think will face resistance from google.
there are some options here:

(0) don't port it, require users to build k8sm-mesos if they want the 'km'
binary and/or k8sm-controller-manager (current state)

(1) port it, and substitute the k8sm-controller-manager for the stock
controller-manager in 'km'; keep k8sm-controller-manager in
kubernetes-mesos for now (will create a bunch of duplicate hypercube code
to be refactored); users are still required to build k8s-mesos if they want
k8sm-controller-manager (required for vanilla mesos clusters)

(2) port it, along with k8sm-controller-manager and see if google allows it
all through (lots of duplicate code in services/endpoint-controller.go)

given that we're pretty time constrained, I'm voting for option (0) ...
@guenter?

**Comment by joerg84** [comment]
We also have to update the ApiVersion to v1beta3 for the example pod.

**Comment by jdef** [comment]
Actually, depending when our changes would land, the apiversion might be
"v1" at that point

**Comment by jdef** [comment]
xref #340

**Comment by jdef** [comment]
updates to the getting-started-guide will leverage the new build scripts that are merging upstream as part of https://github.com/GoogleCloudPlatform/kubernetes/pull/8882

**Comment by jdef** [comment]
the consensus this morning was to wait for the upstream mega-PR's to be merged, then do this doc update

**Comment by davidopp** [comment]
You should go directly to the v1 API.

**Comment by sttts** [comment]
Blocked by #308

**Comment by sttts** [comment]
Started with an update of the getting started guide: https://github.com/mesosphere/kubernetes/tree/update-mesos-getting-started-guide

**Comment by sttts** [comment]
Changed assignee. @joerg84 is in charge of the branch right now.

**Comment by jdef** [comment]
xref https://github.com/GoogleCloudPlatform/kubernetes/pull/9853
