### ISSUE TITLE
kubelet-executor fails to properly kill pod in e2e DNS test

### ISSUE THREAD

**Issue by jdef** [mesosphere/kubernetes-mesos#367]
Executor received kill command, but didn’t kill the container.

> karl [8:55 PM]
> repro with `./cluster/test-e2e.sh -v=2 -ginkgo.focus=DNS.*should.provide.DNS.for.services`

/cc @karlkfi

**Comment by sttts** [comment]
This is fixed in GoogleCloudPlatform/kubernetes#10219

**Comment by sttts** [comment]
Moreover, the "should.provide.DNS.for.services" test is fixed after a rebase of our docker-compose branch to latest master. There was a bug in the e2e dns tests that "tcp" was used as protocol, but "TCP" is only valid. Because our endpoint controller checks the protocol (in contrast to upstream), the test failed for us.

**Comment by jdef** [comment]
The upstream change has been merged. Why was this re-opened?

**Comment by sttts** [comment]
Was reopened before. Now it can be closed.
