### ISSUE TITLE
k8s-mesos conformance with k8s v1 spec/tests

### ISSUE THREAD

**Issue by jdef** [mesosphere/kubernetes-mesos#377]
At the k8s community sync today Google said they were going to label the distributions (identified in the getting started guide) with conformance indicators, e.g. "conforms to v1".

We want to be labelled as such. @karlkfi says that this is probably related to passing a subset of the e2e tests. Need to:

- [x] investigate which e2e tests imply conformance
  - https://github.com/kubernetes/kubernetes/blob/master/hack/conformance-test.sh
- [ ] make sure that we pass these tests
  - test run: https://gist.github.com/sttts/8e2b13348aeb08bb9ee6
  - [ ] #436 
  - [ ] #437 
  - [x] #438 
  - [ ] #439
- [ ] update the getting-started landing page to indicate that we're v1 compliant

**Comment by sttts** [comment]
Some comments about what is left to do for passing all conformance tests (after applying https://github.com/kubernetes/kubernetes/pull/13036, compare https://teamcity.mesosphere.io/viewLog.html?buildId=39359&buildTypeId=Oss_KubernetesMesos_e2eTests)

Currently 5 tests are failing:
- Kubernetes e2e suite.Kubectl client Kubectl expose should create services for rc
- Kubernetes e2e suite.Services should serve a basic endpoint from pods
- Kubernetes e2e suite.Services should serve multiport endpoints from pods

These 3 fail because our special „mesos/docker“ annotation-to-container-port hack in e2e/service.go does not work in conformance test because the provider string is „“. To fix this we have to remove the „mesos/docker“ check there. (https://github.com/mesosphere/kubernetes-mesos/issues/450)

- Kubernetes e2e suite.kubelet Monitor resource usage on node Ask kubelet to report container resource usage 
- Kubernetes e2e suite.ResourceUsage should not exceed expected amount. 

IMO these two tests do not belong into the conformance test suite because they expect that the kubelet can change cgroups of system processes. Compare (https://github.com/mesosphere/kubernetes-mesos/issues/436). We should start a discussion with the Google people about this, maybe something for community sync.

**Comment by jdef** [comment]
FYI, upcoming changes for conformance testing (v1.1.x): kube config file instead of "master ip" setting; https://github.com/kubernetes/kubernetes/commit/29da889bbf0acbf579ea155e4cc66ae168705468#diff-c51e836841b8e562f5297ee6e4a169cb

**Comment by karlkfi** [comment]
Yeah, I got them to fix that. It only ever really required the kube config but the wrapper script required the master url for unknown reasons.

**Comment by karlkfi** [comment]
Since all other conformance failures have their own tickets, I'm closing this meta-ticket in favor of #487 to track updating the getting-started landing page.
