### ISSUE TITLE
Unable to kick off apiserver 

### ISSUE THREAD

**Issue by kolobok01** [mesosphere/kubernetes-mesos#382]
By following the instructions from 
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/mesos.md

When kicking off the 
```./bin/km apiserver \
  --address=${servicehost} \
  --mesos_master=${mesos_master} \
  --etcd_servers=http://${servicehost}:4001 \
  --service-cluster-ip-range=10.10.10.0/24 \
  --port=8888 \
  --cloud_provider=mesos \
  --v=1 >apiserver.log 2>&1 &```

Failing with 
```F0628 22:59:13.385019    4171 server.go:171] No --portal_net specified```

**Comment by jdef** [comment]
we're in the process of updating the docs. please see https://github.com/GoogleCloudPlatform/kubernetes/pull/10072

**Comment by kolobok01** [comment]
Cool. Thanks for the commit and for replying :).

**Comment by F21** [comment]
@kolobok01 The old docs asks you to clone from the kubernetes-mesos repo which uses an older version of kubernetes. In that case replace `--service-cluster-ip-range` with `--portal_net`.

However, the docs were updated a few hours ago to use the latest version of kubernetes which means you can now use `--service-cluster-ip-range`.

**Comment by kolobok01** [comment]
@jdef Hi James thanks for the docs. I have another qq - Is part on how to config and bootstrap proxy is missing  ?

**Comment by jdef** [comment]
By default, kube-proxy is started on mesos slaves when the kubelet-executor
spins up. There's no extra work to get it going there.

If desired, you can still set up a kube-proxy on the master node, using the
master as a poor-man's load balancer; that step was removed from the docs
since we streamlined the example but it should still work as long as you
tell kube-proxy how to find the apiserver --and-- as in the previous
instructions you'd need some additional iptables rules manually installed
for the services that you want to load-balance this way.

**Comment by kolobok01** [comment]
Thanks for the overview. Need to look over docs and imp for better understanding.
