### ISSUE TITLE
show kube-ui from /service/kubernetes/

### ISSUE THREAD

**Issue by sttts** [mesosphere/kubernetes-mesos#483]
Now some JSON self-description of the api is shown. Instead we should redirect to kube-ui.

**Comment by jdef** [comment]
Agreed. We can't do this though because of how frameworkInfo.webui_url is being used within DCOS. The DCOS service proxy currently does this:

- /service/{framework-name}/ -> {FrameworkInfo.webui_url}

If we make FrameworkInfo.webui_url point to kube-ui, then kubectl breaks. What DCOS needs is a smarter way to do service redirection. I've been thinking about this and there might be a hackable solution in the form of the newly added FrameworkInfo.Labels field that's part of mesos v0.24. The idea is to have the following rules in place:
- FrameworkInfo.labels['dcos.service.redirect'] = http://kubernetes.marathon.mesos:{port}/api/
- FrameworkInfo.webui_url = http://kubernetes.marathon.mesos:{port}/api/v1/proxy/namespaces/kube-system/services/kube-ui/#/dashboard/

The end result would be that http://dcos/service/kubernetes/ still redirects to /api/ but the DCOS web interface would use webui_url (via something like http://dcos/webui/kubernetes/). This probably means that the DCOS reverse proxy needs a few extras:
- additional smarts regarding the possible existence of a new label
- in addition to /service/.. redirector there probably needs to be a /webui/ redirector..

For services that don't define a special label, http://dcos/service/kubernetes/ and http://dcos/webui/kubernetes/ would both resolve to the value of frameworkInfo.webui_url

I haven't proposed this yet to the DCOS team, I thought of this on the flight back from SFO this past Fri. Of course, since it depends on mesos v0.24 we'll have to wait a bit before DCOS supports anything like this.

**Comment by sttts** [comment]
The framework webui_url is the apiserver url right now. I was thinking around the lines of redirecting the apiserver / uri to the kube-ui, either statically for every http client or at least for browser user-agents. We will need some kind of proxy for serving the kubectl binaries soon. Then an additional redirect for / is easy.

Of course, here I assume that the current output of / (i.e. the json snippet) is not used anywhere. The kubectl will use the /api endpoint instead AFAIK.

**Comment by jdef** [comment]
Another option is to update DCOS CLI to support mustache templates for
postInstallNotes so that we could generate a clickable link that takes a
user to kube-ui.

**Comment by sttts** [comment]
I would like to have the framework link in the dcos ui to redirect to the kube-ui. This white page with some json looks hacky.

**Comment by jdef** [comment]
Tamar suggested that we have a "dcos k8s get-ui-url" subcommand as a
short-term workaround.

**Comment by sttts** [comment]
I think as soon as we integrate the kubectl subcommand we will have the proxy as well. I wouldn't spend any effort for an alternative solution before. Should be possible in this or the following sprint.
