### ISSUE TITLE
Kubernetes vs. Kubernetes-on-Mesos

### ISSUE THREAD

**Issue by huang195** [mesosphere/kubernetes-mesos#545]
I was able to stand up both kubernetes and kubernetes on mesos following the instructions. However, I'm curious what are some of the differences between the 2 versions of kubernetes. In particular, I noticed that in the kubernetes-on-mesos version, only the kubernetes master components are required to start, and no mention of kubelet or kube-proxy needed to be started on the slave nodes. Are these no longer needed or does mesos start these automatically when new resources are obtained? It would be good to document these (unless I didn't find them). Thanks!

**Comment by karlkfi** [comment]
When running as a mesos framework, the k8sm scheduler will lazily launch kubelets as part of the mesos executor launched on each slave to which a k8s task is scheduled.

The docs, limited tho they are, are here: https://github.com/kubernetes/kubernetes/tree/master/contrib/mesos

Feel free to submit a PR to make them more clear on this point.

**Comment by jdef** [comment]
In general, a mesos framework consists of a scheduler and an executor. An operator is generally required to start the scheduler and then submit tasks to it. The scheduler will spawn executors to executs those tasks.

The k8s-mesos framework is a little more complicated because the operator must start more than just the scheduler: there are several components (apiserver, scheduler, controller-manager, etcd) that need to be up and running before the scheduler will successfully place pods on slave nodes. The k8s-mesos framework **does not** require the operator to start the kubelet or kube-proxy since those are started as part of the executor process, which is spawned on-demand to launch pods.

**Comment by huang195** [comment]
Thanks @karlkfi and @jdef for the quick response. I will take a look at the docs and see if I can help clarify anything missing.

**Comment by huang195** [comment]
I also found this doc link to be useful: https://github.com/kubernetes/kubernetes/blob/master/contrib/mesos/docs/architecture.md
FYI in case others were looking for the same info
