### ISSUE TITLE
Pods saturate only 1 node out of 10

### ISSUE THREAD

**Issue by sttts** [mesosphere/kubernetes-mesos#636]
The mesos cluster has 10 nodes which have same configuration. After k8s framework is registered, mesos send 10 offers and then K8s cached them. When we submit hundred pods to k8s, we found k8s place those pods into one node until the resources of the node are used up, and then put other pods into pending status with message of "No suitable offers for pod/task".

The offers of the left 9 nodes are never returned back to mesos based on mesos UI, scheduler.log of k8s and log file of mesos mater.

**Comment by luckyfengyong** [comment]
I found a root case. The problem is in offerStorage.Add() in offers.go as follows. When detecting incompatible offer, k8s decline the offer and then returned without handling other offers. In our case, all the other 9 offers are ignored by k8s however mesos still think k8s owns them.

func (s *offerStorage) Add(offers []*mesos.Offer) {
	now := time.Now()
	for _, offer := range offers {
		if !s.Compat(offer) {
			//TODO(jdef) would be nice to batch these up
			offerId := offer.Id.GetValue()
			log.V(3).Infof("Declining incompatible offer %v", offerId)
			s.declineOffer(offerId, offer.GetHostname(), metrics.OfferCompat)
			return <-- return without handling the other offers, and then offer leak.
		}

**Comment by jdef** [comment]
nice find!
