### ISSUE TITLE
Not Work kubernetes by using  `dcos pakcage install` 

### ISSUE THREAD

**Issue by letusfly85** [mesosphere/kubernetes-mesos#637]
Hi, I want to run k8s on mesos by using `dcos` CLI tools

I saw below, and tried to kick installing k8s,

https://docs.mesosphere.com/services/kubernetes/

```bash
dcos package install --options=options.json kubernetes
```

however, I cannot get running k8s....

I want to experience k8s on mesos.

Thank you

**Comment by letusfly85** [comment]
Hi, I started etcd below.

```bash
dcos package install --options=etcd-options.json etcd
```

I don't use mesos-dns, so I send some parameters like `mesos.master` by using json like below.


```json
{
  "etcd": {
    "zk": "zk://*.*.*.*:2181/etcd"
  },
  "mesos": {
    "master": "zk://*.*.*.*:2181/mesos"
  }
}
```

**Comment by letusfly85** [comment]
I also use json parameters to start kubernetes, however it doesn't work.
On webui of marathon, k8s is waiting all time..


```bash
dcos package install --options=kubernetes-options.json kubernetes
```

json params is below.


```json
{
  "kubernetes": {
    "etcd-mesos-framework-name": "etcd"
 },
  "mesos": {
    "master": "zk://*.*.*.*:2181/mesos"
  }
}
```

**Comment by letusfly85** [comment]
I used Mesos-dns, however, k8s doesn't start..
still waiting.

What's wrong?

**Comment by jdef** [comment]
Are you attempting to deploy to a DCOS cluster, or a home-brewed mesos cluster w/ mesos-dns?

**Comment by letusfly85** [comment]
I'm trying to deploy to a DCOS cluster, I installed mesos-master, mesos-slave, marathon by seeing below.

https://open.mesosphere.com/getting-started/install/

I use AWS ec2 instances for cluster.

node1 => mesos-master, marathon
node2 => mesos-slave
node3 => mesos-dns 

Why I use mesos-dns is that I though marathon has to detect mesos-master and zookeeper address by DNS such as `zk://master.mesos:2181/mesos`.
It seems that  `dcos package` utility uses some environment values in `marathon.json`, `config.json`, and so on. (I see https://github.com/mesosphere/multiverse/tree/version-1.x/repo/packages/K/kubernetes/2)
And some of json parameters include `master.mesos` for detecting address of mesos-master and zookeeper.

So, I use mesos-dns to detect DNS.
However, when I use mesos-dns and when I don't use mesos-dns and specify address of master.mesos by `options=my.json`, k8s doesn't start.....

**Comment by letusfly85** [comment]
After I failed to deploy k8s, I tried some of universe and multiverse repositories on my cluseter,
some of packages (etcd, cassandra, arangodb, kafka) worked (it's cool).
However, some of packages didn't work....such as spark.

Where should I check, I want to know.
mesos-master, slave don't give any log.. and marathon didn't show any log on OS.

And especially, I want to use k8s.

**Comment by jdef** [comment]
Our dev team doesn't test the DCOS package in any environment than the one provisioned by Mesosphere's DCOS templates/tooling. It sounds like you're standing up your own pseudo-DCOS cluster. So my gut response is: YMMV.

I'm having difficulty understanding how you've set up DNS in your cluster. You may be interested in setting the kubernetes package `dns-suffix` value to coincide with your mesos-dns domain. The packaging makes some assumptions about how k8s components can locate each other via mesos-dns.

**Comment by letusfly85** [comment]
I see... thank you. Yes, I'm trying to provision by DCOS template/tooling.
I will create a issue to [multiverse](https://github.com/mesosphere/multiverse) or [marathon](https://github.com/mesosphere/marathon) to find the way of debugging mesos, dcos, marathon..

Mesos-dns construct was little difficult, I downloaded binary Mesos-dns package from github, and run it on mesos-dns node. after that, I rewrite mesos-master and mesos-slave node's `/etc/resolve.conf`.
From mesos-master and mesos-slave, I can detect `master.mesos`, `marathon.mesos` and so on.

**Comment by letusfly85** [comment]
I did it below.

https://github.com/mesosphere/multiverse/issues/50

I can close this issue. thank you.

**Comment by karlkfi** [comment]
This is the preferred repo for reporting Kubernetes on Mesos/DCOS issues. Posting on the multiverse repo won't get you any special support, since the maintainers of this repo also maintain the Kubernetes package there.

The reason we don't have much advice to give you is that we only support (and have experience with) the Kubernetes DCOS package installed on DCOS Community Edition or Enterprise Edition. By creating your own "fake" DCOS cluster, your networking, topology, and interconnectivity characteristics are unknown and unsupportable. We have no way to duplicate your setup. You might be able to get dcos-cli working on a non-dcos mesos-based stack, but that doesn't make it a real, officially supported DCOS cluster.

If you want to try DCOS, we recommend using the [DCOS Community Edition on AWS](https://mesosphere.com/amazon/).

If you want to try Kubernetes on Mesos without DCOS, try the [Kubernetes on Mesos guide](https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/mesos.md).

**Comment by letusfly85** [comment]
Thank you for replying. I understood that my env is fake and not real cluster.

I will try to use DCOS Community Edition on AWS.

However, what is the purpose below manually installing guide? :sweat_drops:  (even if you, owners, recommend to use packaged solution like 'DCOS Community Edition on AWS')
https://open.mesosphere.com/getting-started/install/

It seems like that it will mislead some developpers.. :sweat_drops:

**Comment by karlkfi** [comment]
I agree, the present state of the docs and their discoverability is a bit confusing. Let me try to clarify.

The https://open.mesosphere.com/ docs are primarily for community documentation of several OSS components that Mesosphere has written or contributed to, primary focusing on Mesos, Marathon and Chronos. These components make up what used to be called the "Mesosphere stack", but now don't have an offical name. You could call it a "Mesos/Marathon stack", I guess. There are dozens of ways to put these components together. So it's pretty hard to support. 

However, in more recent history, Mesosphere started offering DCOS as a product, which uses those core components and builds upon them with additional components (some OSS and some proprietary). DCOS documentation is at https://docs.mesosphere.com/ This is our official product and the primary target for our Kubernetes integration.

So while you can deploy your own "Mesos stack" you're effectively rolling your own cluster. Mesosphere may offer for-pay corporate support plans for this kind of thing, but they don't yet include Kubernetes support (at least until we're out of alpha).

The [Kubernetes on Mesos guide](https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/mesos.md) is for integrating Kubernetes with Mesos without DCOS. Currently, it's a little complicated, and requires familiarity with both Kubernetes and Mesos. We do plan to make the process and guide easier to follow (ex: #609). This is the guide we recommend when not using DCOS, because it familiarizes the admin with more details about the integration.

The [Kubernetes on DCOS guide](https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/dcos.md) is for installing Kubernetes on the CE or EE of DCOS. It is the easiest way to install Kubernetes using the Mesos framework, but currently requires an official DCOS cluster, which makes it much easier for use to duplicate the customer's environment.

**Comment by letusfly85** [comment]
Thank you, I understood..

I will try to talk about DCOS to our team, and will reconsider about mesosphere solutions.

Thank you.
